import { Geist, Geist_Mono } from "next/font/google";
import "./../globals.css";
import Navbar from "@/components/ui/navbar"
import { SessionProvider } from "@/components/providers/session-provider"
import { ModalProvider } from "@/components/providers/modal-provider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function UnprotectedLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionProvider>
          <ModalProvider />
          <Navbar />
          <main className="">
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
