import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./../../globals.css";
import { SessionProvider } from "@/components/providers/session-provider"
import { DashboardNavbar } from "@/components/dashboard/navbar";
import { Toaster } from "@/components/ui/sonner"
import { BreadcrumbProvider } from "@/contexts/breadcrumb-context";
import { ModalProvider } from "@/components/providers/modal-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <BreadcrumbProvider>
          <ModalProvider/>
            <DashboardNavbar/>
            <main className="pt-14">
              {children}
            </main>
            <Toaster />
          </BreadcrumbProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
